# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Automation WorkFlow

on:
  schedule:
  - cron: 30 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=false

    - name: Upload  Test logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: Test logs
       path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: screenshots
        path: screenshots/

    - name: Upload HTML Report as Artifact
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: html-report
        path: report.html
       
    - name: Test Execution Status
      if: always()
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages Folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html  public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l

    - name: Deploy ðŸš€
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{ secrets.PAges }}
        clean: true
